### ISSUE TITLE
Create Selector class to implement multiple selections

### ISSUE THREAD

**Issue by jpricarte** [jpricarte/simple-heuristic#4]
## About
Create a Selector class, that will be used to select elements using a internal policy

## To-do
- [x] Create a generic base class
- [x] Create a Random class to support the current method
- [x] Create a Greedy class to support a basic method
- [x] Add a Selector attribute into the parser
