### ISSUE TITLE
Add Selector in the algorithms

### ISSUE THREAD

**Issue by jpricarte** [jpricarte/simple-heuristic#5]
## About

Change all the algorithms to use the Selector class, excluding the old selection function

## To-Do
- [x] Add the selector to Constructive Algorithms
- [x] Change the signature and internal implementations
- [x] Test and Validation
