### ISSUE TITLE
Parse Selector

### ISSUE THREAD

**Issue by jpricarte** [jpricarte/simple-heuristic#6]
## About

Implement the Selector parsing, to update the module

## To-do

- [x] Create Methods for parsing
- [x] Remove old parsing
- [x] Make it generic and expandable
